Inheritance (#54)
* automated patching [ci skip]

* automated patching [ci skip]

* Merge branch 'master' of github.com:sabeurthabti/react-native-css

# Conflicts:
#	README.md
#	package.json

* Adding sass support

* automated patching [ci skip]

* Adding sass support

* Adding sass support

* automated patching [ci skip]

* Adding sass support

* Adding sass support

* Update README.md

* Update README.md

* Update README.md

* automated patching [ci skip]

* Update README.md

* Adding sass support

* automated patching [ci skip]

* Adding sass support

* automated patching [ci skip]

* Adding sass support

* automated patching [ci skip]

* automated patching [ci skip]

* Adding sass support

* automated patching [ci skip]

* Adding sass support

* Adding sass support

* automated patching [ci skip]

* ensuring numbers are not string.

* automated patching [ci skip]

* Update README.md

* Update README.md

* ensuring numbers are not string.

* automated patching [ci skip]

* Update package.json

* Update package.json

* automated patching [ci skip]

* Update package.json

* automated patching [ci skip]

* Added option to pretty print output.

* automated patching [ci skip]

* Update README.md

* automated patching [ci skip]

* adding npm badge, for number of downloads.

* automated patching [ci skip]

* Update README.md

* Hotfix on add wrong path to input file

node_modules/react-native-css/build/index.js:266
		return string.replace(/\r?\n|\r/g, "");
		             ^

TypeError: Cannot read property 'replace' of undefined

* beautify code

* automated patching [ci skip]

* automated patching [ci skip]

* Fix handleRulesAndReturnCSSJSON returning undefined if any comments exist

I'm trying to get this package working (it just outputs `undefined` as the stylesheet for me at the moment) and noticed this obvious bug. I'm not sure if what I've done here is sufficient to fix everything, but it can't hurt.

* Update package.json

* automated patching [ci skip]

* automated patching [ci skip]

* ensure watch is working

* automated patching [ci skip]

* es2015 class

* readme

* automated patching [ci skip]

* simple improvements, and notifying users when package is out of date

* automated patching [ci skip]

* fix: transform all styles, not only first block

closes #20

* fix: ensure font-weight property is stringified as required by react native

* automated patching [ci skip]

* adding tests for all issues

* adding tests for all issues

* automated patching [ci skip]

* Issue #22: Ignore unsupported properties and parse the "width" property

* Parse width as well

* Parse width and font-size

* Parse width and font-size

* automated patching [ci skip]

* bump

* build file

* automated patching [ci skip]

* cb fix

* cb fix

* cb fix

* cb fix

* more fixing

* fix

* fix

* circle-ci push

* circle-ci push

* clean up

* patching

* 1.2.31

* clean up

* 1.2.32

* Update circle.yml

* Update circle.yml

* Update circle.yml

* automated patching [ci skip]

* Issue #22: Adding tests

* automated patching [ci skip]

* Update circle.yml

* automated patching [ci skip]

* Link to node_modules/bin is unnecessary as npm adds it to the PATH on script execution

* Add height to numberize properties

* Split spaces for condensed properties
eg. margin 10px 10px 10px 5px

* Fix #26 by adding more numberize properties

* automated patching [ci skip]

* Use more reliable writeFileSync

* Rebuild

* Fix tab style

* automated patching [ci skip]

* Use parseFloat instead of int to fix `opacity: 0.6` getting set to 0 by parseInt

* Rebuild products

* automated patching [ci skip]

* Adding --literal argument to generate js literal object

* --literal argument adding test

* automated patching [ci skip]

* Update package.json

* automated patching [ci skip]

* Add MIT License

* automated patching [ci skip]

* Update README.md

* automated patching [ci skip]

* - Fixed 2 parameter shorthands not expanding Left, Right values
- Added border-width and border-radius shorthand expansion support

* automated patching [ci skip]

* [skip ci]

*  - Added border shorthand support, including directions
 - Removed expansion for single value shorthand

* Added inheritance flag
Added className wrapper & related functionality
Added examples of using className component

* Fixed border expansion test

* Update react version

* Converted parse to async/await, removing callback
Made output optional
Added eslint config & linted
Upgraded to babel 6
Added check for web environment (react-native-web)
Added path cache (reduces array operations)
Converted tests to Jest

* Updated README.md for styled components

* Moved to using _reactInternalInstance to calculate sibling position, not public API but works and avoids having to map

* Only pass prop.style if exisits

* Added --silent to circle.yml to fix CI error peer dependency

* Check if npm update fixes peer depencies fail

* Specify node version in circle-ci

* Specify node version in circle-ci

* Added babel transform
Synchronized parse
Watcher for babel

* Updated versions
Fix babel file include

* Fix bable transform relative path